---
- hosts: testnodes
  become: yes
  tasks:
   - name: Log into docker hub
     command: docker login -u sy007 -p Anilkumarsy6224
   - name: Build an image and push it to a private repo
     community.docker.docker_image:
        build:
              path: "/home/ansibleadmin/"
        name: docker.io/sy007/abctechnologies
        #tag: test
        push: true
        source: build
     register: out
   - debug:
        var: out
   - name: start a container
     community.docker.docker_container:
        name: abc-application
        image: sy007/abctechnologies
        state: started
        ports:
              - 1234:8080
        #restart: true
     register: out
   - debug:
        var: out
        #- name: Deploying to kubernetes
   - name: Create a Deployment by reading the definition from a local fil
     command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f
                /home/ansibleadmin/deployment.yml"
     register: out
   - debug:
        var: out
